//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntoItIf.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntoItIf.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection string must be passed to the constructor.
        /// </summary>
        internal static string AConnectionStringMustBePassedToTheConstructor {
            get {
                return ResourceManager.GetString("AConnectionStringMustBePassedToTheConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in your Application.
        /// </summary>
        internal static string An_error_occurred_in_your_Application {
            get {
                return ResourceManager.GetString("An_error_occurred_in_your_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte[] value greater than 20megs are not supported.
        /// </summary>
        internal static string ByteValueGreaterThan20megsAreNotSupported {
            get {
                return ResourceManager.GetString("ByteValueGreaterThan20megsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Configuration method is no longer supported. Use a Provider configuration instead..
        /// </summary>
        internal static string ConfigurationMethodNoLongerSupported {
            get {
                return ResourceManager.GetString("ConfigurationMethodNoLongerSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection opening failure: {0}.
        /// </summary>
        internal static string ConnectionOpeningFailure {
            get {
                return ResourceManager.GetString("ConnectionOpeningFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load entity - invalid key provided..
        /// </summary>
        internal static string CouldntLoadEntityInvalidKeyProvided {
            get {
                return ResourceManager.GetString("CouldntLoadEntityInvalidKeyProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader passed to DataReaderToObject cannot be closed.
        /// </summary>
        internal static string DataReaderPassedToDataReaderToObjectCannot {
            get {
                return ResourceManager.GetString("DataReaderPassedToDataReaderToObjectCannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string ErrorColon {
            get {
                return ResourceManager.GetString("ErrorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection String..
        /// </summary>
        internal static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection string name..
        /// </summary>
        internal static string InvalidConnectionStringName {
            get {
                return ResourceManager.GetString("InvalidConnectionStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encryptipon property name.
        /// </summary>
        internal static string InvalidEncryptionPropertyName {
            get {
                return ResourceManager.GetString("InvalidEncryptionPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex digit: .
        /// </summary>
        internal static string InvalidHexDigit {
            get {
                return ResourceManager.GetString("InvalidHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex string length: {0}.
        /// </summary>
        internal static string InvalidHexStringLength {
            get {
                return ResourceManager.GetString("InvalidHexStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for XmlType to .NET Type conversion..
        /// </summary>
        internal static string InvalidTypeForXmlTypeToNETTypeConversion {
            get {
                return ResourceManager.GetString("InvalidTypeForXmlTypeToNETTypeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML configuration file format in {0}..
        /// </summary>
        internal static string InvalidXMLConfigurationFileFormat {
            get {
                return ResourceManager.GetString("InvalidXMLConfigurationFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.NET library not avaiable. Please add the Newtonsoft.Json package to your project..
        /// </summary>
        internal static string JSON_NET_library_not_avaiable {
            get {
                return ResourceManager.GetString("JSON_NET_library_not_avaiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing encryption key..
        /// </summary>
        internal static string MissingEncryptionKey {
            get {
                return ResourceManager.GetString("MissingEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active Transaction to commit..
        /// </summary>
        internal static string NoActiveTransactionToCommit {
            get {
                return ResourceManager.GetString("NoActiveTransactionToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object could not be deserialized from Xml..
        /// </summary>
        internal static string ObjectCouldNotBeDeserializedFromXml {
            get {
                return ResourceManager.GetString("ObjectCouldNotBeDeserializedFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sql Server Compact data provider is not supported on .NET Core.
        /// </summary>
        internal static string SqlServerCompactDataProviderNotSupportedOnNetCore {
            get {
                return ResourceManager.GetString("SqlServerCompactDataProviderNotSupportedOnNetCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Conversion not handled in StringToTypedValue for .
        /// </summary>
        internal static string StringToTypedValueValueTypeConversionFailed {
            get {
                return ResourceManager.GetString("StringToTypedValueValueTypeConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read configuration string from Sql Server field..
        /// </summary>
        internal static string UnableToExtractKeys {
            get {
                return ResourceManager.GetString("UnableToExtractKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read config information from string..
        /// </summary>
        internal static string UnableToReadConfigDataFromString {
            get {
                return ResourceManager.GetString("UnableToReadConfigDataFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve DbProviderFactory for: {0}.
        /// </summary>
        internal static string UnableToRetrieveDbProviderFactoryForm {
            get {
                return ResourceManager.GetString("UnableToRetrieveDbProviderFactoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Provider Factory specified: {0}.
        /// </summary>
        internal static string UnsupportedProviderFactory {
            get {
                return ResourceManager.GetString("UnsupportedProviderFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
